/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["postApiAuthRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login to get access token */
        post: operations["postApiAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current user */
        post: operations["postApiAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard summary */
        get: operations["getApiActivitiesHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user activities */
        get: operations["getApiActivities"];
        put?: never;
        /** Create new activity */
        post: operations["postApiActivities"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get activity detail */
        get: operations["getApiActivitiesById"];
        put?: never;
        post?: never;
        /** Delete activity */
        delete: operations["deleteApiActivitiesById"];
        options?: never;
        head?: never;
        /** Update activity */
        patch: operations["patchApiActivitiesById"];
        trace?: never;
    };
    "/api/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getApiUsersProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user profile */
        patch: operations["patchApiUsersProfile"];
        trace?: never;
    };
    "/api/upload/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload avatar image (Proxy to file-service) */
        post: operations["postApiUploadAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload activity image (Proxy to file-service) */
        post: operations["postApiUploadActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "auth.register": {
            username: string;
            /** Format: email */
            email: string;
            password: string;
        };
        "auth.login": {
            /** Format: email */
            email: string;
            password: string;
        };
        "activity.create": {
            title: string;
            description?: string;
            scheduledAt?: string;
            imageUrl?: string;
        };
        "activity.update": {
            title?: string;
            description?: string;
            scheduledAt?: string;
            isCompleted?: boolean;
            imageUrl?: string;
        };
        "activity.params": {
            id: string | number;
        };
        "activity.query": {
            /** @default 10 */
            limit: string | number;
            /** @default 0 */
            offset: string | number;
            completed?: boolean | string;
            search?: string;
        };
        "activity.response": {
            id: number;
            title: string;
            description: string | null;
            isCompleted: boolean;
            scheduledAt: (Record<string, never> | string | number) | null | string;
            createdAt: unknown;
            userId: number;
            imageUrl: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getApiHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postApiAuthRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["auth.register"];
                "multipart/form-data": components["schemas"]["auth.register"];
                "text/plain": components["schemas"]["auth.register"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        user: {
                            id: number;
                            username: string;
                            email: string;
                        };
                    };
                    "multipart/form-data": {
                        message: string;
                        user: {
                            id: number;
                            username: string;
                            email: string;
                        };
                    };
                    "text/plain": {
                        message: string;
                        user: {
                            id: number;
                            username: string;
                            email: string;
                        };
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                    "multipart/form-data": {
                        message: string;
                    };
                    "text/plain": {
                        message: string;
                    };
                };
            };
        };
    };
    postApiAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["auth.login"];
                "multipart/form-data": components["schemas"]["auth.login"];
                "text/plain": components["schemas"]["auth.login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        token: string;
                    };
                    "multipart/form-data": {
                        message: string;
                        token: string;
                    };
                    "text/plain": {
                        message: string;
                        token: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        token: null;
                    };
                    "multipart/form-data": {
                        message: string;
                        token: null;
                    };
                    "text/plain": {
                        message: string;
                        token: null;
                    };
                };
            };
        };
    };
    postApiAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                    "multipart/form-data": {
                        message: string;
                    };
                    "text/plain": {
                        message: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                    "multipart/form-data": {
                        message: string;
                    };
                    "text/plain": {
                        message: string;
                    };
                };
            };
        };
    };
    getApiActivitiesHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getApiActivities: {
        parameters: {
            query?: {
                limit?: string | number;
                offset?: string | number;
                completed?: boolean | string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    }[];
                    "multipart/form-data": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    }[];
                    "text/plain": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    }[];
                };
            };
        };
    };
    postApiActivities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["activity.create"];
                "multipart/form-data": components["schemas"]["activity.create"];
                "text/plain": components["schemas"]["activity.create"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    };
                    "multipart/form-data": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    };
                    "text/plain": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    };
                };
            };
        };
    };
    getApiActivitiesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string | number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    };
                    "multipart/form-data": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    };
                    "text/plain": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                    "multipart/form-data": {
                        message: string;
                    };
                    "text/plain": {
                        message: string;
                    };
                };
            };
        };
    };
    deleteApiActivitiesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string | number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                    "multipart/form-data": {
                        message: string;
                    };
                    "text/plain": {
                        message: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                    "multipart/form-data": {
                        message: string;
                    };
                    "text/plain": {
                        message: string;
                    };
                };
            };
        };
    };
    patchApiActivitiesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string | number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["activity.update"];
                "multipart/form-data": components["schemas"]["activity.update"];
                "text/plain": components["schemas"]["activity.update"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    };
                    "multipart/form-data": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    };
                    "text/plain": {
                        id: number;
                        title: string;
                        description: string | null;
                        isCompleted: boolean;
                        scheduledAt: (Record<string, never> | string | number) | null | string;
                        createdAt: unknown;
                        userId: number;
                        imageUrl: string | null;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                    "multipart/form-data": {
                        message: string;
                    };
                    "text/plain": {
                        message: string;
                    };
                };
            };
        };
    };
    getApiUsersProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        email: string;
                        username: string;
                        avatarUrl: string | null;
                        createdAt: unknown;
                    };
                    "multipart/form-data": {
                        id: number;
                        email: string;
                        username: string;
                        avatarUrl: string | null;
                        createdAt: unknown;
                    };
                    "text/plain": {
                        id: number;
                        email: string;
                        username: string;
                        avatarUrl: string | null;
                        createdAt: unknown;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                    "multipart/form-data": {
                        message: string;
                    };
                    "text/plain": {
                        message: string;
                    };
                };
            };
        };
    };
    patchApiUsersProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username?: string;
                    email?: string;
                    avatarUrl?: string;
                };
                "multipart/form-data": {
                    username?: string;
                    email?: string;
                    avatarUrl?: string;
                };
                "text/plain": {
                    username?: string;
                    email?: string;
                    avatarUrl?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        email: string;
                        username: string;
                        avatarUrl: string | null;
                        createdAt: unknown;
                    };
                    "multipart/form-data": {
                        id: number;
                        email: string;
                        username: string;
                        avatarUrl: string | null;
                        createdAt: unknown;
                    };
                    "text/plain": {
                        id: number;
                        email: string;
                        username: string;
                        avatarUrl: string | null;
                        createdAt: unknown;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                    "multipart/form-data": {
                        message: string;
                    };
                    "text/plain": {
                        message: string;
                    };
                };
            };
        };
    };
    postApiUploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
                "text/plain": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postApiUploadActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
                "text/plain": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
